#!/bin/sh /etc/rc.common
START=90
STOP=15

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

run_jmuEportalAuth()
{
	local enable=$(uci_get_by_type jmuEportalAuth enable)
	local username=$(uci_get_by_type jmuEportalAuth username)
	local password=$(uci_get_by_type jmuEportalAuth password)
	local services=$(uci_get_by_type jmuEportalAuth services)
	local cronset=$(uci_get_by_type jmuEportalAuth cronset)

	if [ $enable ] && [ $password ] && [ $username ]; then
		if [ $services -ge 0 ] && [ $services -le 3 ]; then
			jmuEportalAuth -s $services -u $username -p $password
		else
			jmuEportalAuth -s 0 -u $username -p $password
		fi
	fi

	crontab_file="/etc/crontabs/root"
	if [ $enable ] && [ $cronset ]; then
		if [ ! -f $crontab_file ]; then
			touch $crontab_file
			sleep 1
			echo "5  6  *  *  *  /bin/jmuEportalAuth -r" >> $crontab_file
		else
			sed -i '/jmuEportalAuth/d' $crontab_file
			sleep 1
			echo "5  6  *  *  *  /bin/jmuEportalAuth -r" >> $crontab_file
		fi
	else
		sed -i '/jmuEportalAuth/d' $crontab_file
	fi
}

start()
{
	run_jmuEportalAuth
}

stop()
{
	jmuEportalAuth -k
	killall jmuEportalAuth
}

restart()
{
	jmuEportalAuth -k
	stop
	start
}
